# Generated by Django 2.0.2 on 2018-02-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
    ]
