# Data Structures

## Department GET (object)

+ id: `1` (number, required) - ID
+ name: `Department of Silly Walks` (string, required) - Name of the Department
+ description: `This the department in charge of walks that are silly.` (string, required) - Description
+ address: `Rua dos Bobos, Número Zero` (string, optional) - Address of the Department
+ head: `1` (number, optional) - ID of the Employee in charge of the Department


## Department POST (object)

+ id: `1` (number, required) - ID
+ name: `Department of Silly Walks` (string, required) - Name of the Department
+ description: `This the department in charge of walks that are silly.` (string, required) - Description
+ address: `Rua dos Bobos, Número Zero` (string, optional) - Address of the Department
+ head: `1` (number, optional) - ID of the Employee in charge of the Department

## Department PUT (object)

+ id: `1` (number, required) - ID
+ name: `Department of Silly Walks` (string, required) - Name of the Department
+ description: `This the department in charge of walks that are silly.` (string, required) - Description
+ address: `Rua dos Bobos, Número Zero` (string, optional) - Address of the Department
+ head: `1` (number, optional) - ID of the Employee in charge of the Department

## Department PATCH (object)

+ id: `1` (number, required) - ID
+ name: `Department of Silly Walks` (string, optional) - Name of the Department
+ description: `This the department in charge of walks that are silly.` (string, optional) - Description
+ address: `Rua dos Bobos, Número Zero` (string, optional) - Address of the Department
+ head: `1` (number, optional) - ID of the Employee in charge of the Department

## Employee GET (object)

+ id: `1` (number, required) - ID
+ name: `Rick Sanchez` (string, required) - Name
+ email: `rick.sanchez@fakecompany.com` (string, required) - E-mail
+ phone: `48873244333` (number, required) - Telephone
+ date_joined: `2018-01-15T10:30:30` (string, required) - Date Employee joined the database


## Employee POST (object)

+ id: `1` (number, required) - ID
+ name: `Rick Sanchez` (string, required) - Name
+ email: `rick.sanchez@fakecompany.com` (string, required) - E-mail
+ phone: `48873244333` (number, required) - Telephone
+ date_joined: `2018-01-15T10:30:30` (string, required) - Date Employee joined the database

## Employee PUT (object)

+ id: `1` (number, required) - ID
+ name: `Rick Sanchez` (string, required) - Name
+ email: `rick.sanchez@fakecompany.com` (string, required) - E-mail
+ phone: `48873244333` (number, required) - Telephone
+ date_joined: `2018-01-15T10:30:30` (string, required) - Date Employee joined the database

## Employee PATCH (object)

+ id: `1` (number, optional) - ID
+ name: `Rick Sanchez` (string, optional) - Name
+ email: `rick.sanchez@fakecompany.com` (string, optional) - E-mail
+ phone: `48873244333` (number, optional) - Telephone
+ date_joined: `2018-01-15T10:30:30` (string, optional) - Date Employee joined the database
